pip install asyncio
pip install random
pip install string
pip install time
pip install discord
pip install json
pip install requests
pip install blockcypher
pip install pycoingecko
pip install urllib3
pip install datetime